run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
  revive:
    confidence: 0.8

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0
