coverage:
  precision: 1
  round: down
  range: 70..100

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "header, diff, changes, uncovered, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*_test.go"
  - "**/mocks_test.go"
  - "cmd/lambda/main.go"
  - "cmd/local/main.go"
