version: '3'

tasks:
  build:
    desc: Build Lambda binary for linux/arm64
    cmds:
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o bootstrap ./cmd/lambda/

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  lint-fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix

  goreg:
    desc: Check import organization with goreg
    cmds:
      - |
        FAIL=0
        for f in $(find . -name "*.go" ! -path "./vendor/*"); do
          if ! goreg "$f" | diff -q "$f" - >/dev/null 2>&1; then
            echo "Import organization issue: $f"
            FAIL=1
          fi
        done
        [ $FAIL -eq 0 ] || exit 1

  goreg-fix:
    desc: Fix import organization with goreg
    cmds:
      - |
        for f in $(find . -name "*.go" ! -path "./vendor/*"); do
          goreg -w "$f"
        done

  build-check:
    desc: Verify build without producing binary
    cmds:
      - go build -o /dev/null ./cmd/lambda/

  ci-check:
    desc: Run test, lint, goreg, and build checks in parallel (for local verification)
    deps: [test, lint, goreg, build-check]

  package:
    desc: Package Lambda function into lambda.zip
    deps: [build]
    cmds:
      - zip -j lambda.zip bootstrap

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f bootstrap lambda.zip

  run-local:
    desc: Run locally and preview events (no Discord notification)
    cmds:
      - go run ./cmd/local/

  run-local-send:
    desc: Run locally and send notification to Discord (requires DISCORD_WEBHOOK_URL)
    cmds:
      - go run ./cmd/local/ --send

  init:
    desc: Initialize Terraform
    dir: terraform
    cmds:
      - terraform init

  plan:
    desc: Run Terraform plan
    deps: [package]
    dir: terraform
    cmds:
      - terraform plan

  apply:
    desc: Apply Terraform changes
    deps: [package]
    dir: terraform
    cmds:
      - terraform apply

  apply-ci:
    desc: Apply Terraform changes with auto-approve (for CI/CD)
    deps: [package]
    dir: terraform
    cmds:
      - terraform apply -auto-approve

  deploy:
    desc: Build, package, and deploy to AWS
    cmds:
      - task: build
      - task: package
      - task: apply

  destroy:
    desc: Destroy all AWS resources
    dir: terraform
    cmds:
      - terraform destroy

  # Terraform validation tasks
  tf-fmt:
    desc: Format Terraform files
    dir: terraform
    cmds:
      - terraform fmt -recursive

  tf-fmt-check:
    desc: Check Terraform formatting
    dir: terraform
    cmds:
      - terraform fmt -check -recursive -diff

  tf-validate:
    desc: Validate Terraform configuration
    dir: terraform
    cmds:
      - terraform init -backend=false
      - terraform validate

  tf-lint:
    desc: Run TFLint on Terraform files
    dir: terraform
    cmds:
      - tflint --init
      - tflint --format compact

  tf-security:
    desc: Run tfsec security scan
    dir: terraform
    cmds:
      - tfsec . --format default

  tf-docs:
    desc: Generate Terraform documentation
    dir: terraform
    cmds:
      - terraform-docs .

  tf-check:
    desc: Run all Terraform validation checks (format, validate, lint, security)
    deps: [tf-fmt-check, tf-validate, tf-lint, tf-security]

  tf-fix:
    desc: Auto-fix Terraform formatting and regenerate docs
    cmds:
      - task: tf-fmt
      - task: tf-docs
