version: '3'

tasks:
  build:
    desc: Build Lambda binary for linux/arm64
    cmds:
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o bootstrap ./cmd/lambda/

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  lint-fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix

  goreg:
    desc: Check import organization with goreg
    cmds:
      - |
        MODULE="github.com/Eagle-Konbu/shin-yokohama-event-notifier"
        FAIL=0
        for f in $(find . -name "*.go" ! -path "./vendor/*"); do
          if ! goreg -l "$MODULE" "$f" | diff -q "$f" - >/dev/null 2>&1; then
            echo "Import organization issue: $f"
            FAIL=1
          fi
        done
        [ $FAIL -eq 0 ] || exit 1

  goreg-fix:
    desc: Fix import organization with goreg
    cmds:
      - |
        MODULE="github.com/Eagle-Konbu/shin-yokohama-event-notifier"
        find . -name "*.go" ! -path "./vendor/*" -exec goreg -w -l "$MODULE" {} \;

  build-check:
    desc: Verify build without producing binary
    cmds:
      - go build -o /dev/null ./cmd/lambda/

  ci-check:
    desc: Run test, lint, goreg, and build checks in parallel (for local verification)
    deps: [test, lint, goreg, build-check]

  package:
    desc: Package Lambda function into lambda.zip
    deps: [build]
    cmds:
      - zip -j lambda.zip bootstrap

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f bootstrap lambda.zip

  init:
    desc: Initialize Terraform
    dir: terraform
    cmds:
      - terraform init

  plan:
    desc: Run Terraform plan
    deps: [package]
    dir: terraform
    cmds:
      - terraform plan

  apply:
    desc: Apply Terraform changes
    deps: [package]
    dir: terraform
    cmds:
      - terraform apply

  apply-ci:
    desc: Apply Terraform changes with auto-approve (for CI/CD)
    deps: [package]
    dir: terraform
    cmds:
      - terraform apply -auto-approve

  deploy:
    desc: Build, package, and deploy to AWS
    cmds:
      - task: build
      - task: package
      - task: apply

  destroy:
    desc: Destroy all AWS resources
    dir: terraform
    cmds:
      - terraform destroy
