formatter: "markdown table"

version: ""

header-from: main.tf

footer-from: ""

sections:
  show:
    - header
    - inputs
    - outputs
    - providers
    - requirements

content: |-
  # Terraform Configuration

  ## Usage

  This Terraform configuration manages AWS infrastructure for the shin-yokohama-event-notifier project.

  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
