// Code generated by MockGen. DO NOT EDIT.
// Source: event_fetcher.go
//
// Generated by this command:
//
//	mockgen -source=event_fetcher.go -destination=mock_ports/mock_event_fetcher.go -package=mock_ports
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"
	time "time"

	event "github.com/Eagle-Konbu/shin-yokohama-event-notifier/internal/domain/event"
	gomock "go.uber.org/mock/gomock"
)

// MockEventFetcher is a mock of EventFetcher interface.
type MockEventFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventFetcherMockRecorder
	isgomock struct{}
}

// MockEventFetcherMockRecorder is the mock recorder for MockEventFetcher.
type MockEventFetcherMockRecorder struct {
	mock *MockEventFetcher
}

// NewMockEventFetcher creates a new mock instance.
func NewMockEventFetcher(ctrl *gomock.Controller) *MockEventFetcher {
	mock := &MockEventFetcher{ctrl: ctrl}
	mock.recorder = &MockEventFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventFetcher) EXPECT() *MockEventFetcherMockRecorder {
	return m.recorder
}

// FetchEvents mocks base method.
func (m *MockEventFetcher) FetchEvents(ctx context.Context, from, to time.Time) ([]event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEvents", ctx, from, to)
	ret0, _ := ret[0].([]event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchEvents indicates an expected call of FetchEvents.
func (mr *MockEventFetcherMockRecorder) FetchEvents(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEvents", reflect.TypeOf((*MockEventFetcher)(nil).FetchEvents), ctx, from, to)
}

// VenueID mocks base method.
func (m *MockEventFetcher) VenueID() event.VenueID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VenueID")
	ret0, _ := ret[0].(event.VenueID)
	return ret0
}

// VenueID indicates an expected call of VenueID.
func (mr *MockEventFetcherMockRecorder) VenueID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VenueID", reflect.TypeOf((*MockEventFetcher)(nil).VenueID))
}
